/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface MyComponent2 {}
}

declare namespace LocalJSX {
  interface MyComponent2 extends JSXBase.HTMLAttributes {}

  interface ElementInterfaces {
    'MyComponent2': Components.MyComponent2;
  }

  interface IntrinsicElements {
    'MyComponent2': LocalJSX.MyComponent2;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {


  interface HTMLMyComponent2Element extends Components.MyComponent2, HTMLStencilElement {}
  var HTMLMyComponent2Element: {
    prototype: HTMLMyComponent2Element;
    new (): HTMLMyComponent2Element;
  };
  interface HTMLElementTagNameMap {
    'my-component-2': HTMLMyComponent2Element
  }

  interface ElementTagNameMap {
    'my-component-2': HTMLMyComponent2Element;
  }
}

